/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Arnobkumarsaha/custom-controller/pkg/apis/arnob.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMessis implements MessiInterface
type FakeMessis struct {
	Fake *FakeArnobV1alpha1
	ns   string
}

var messisResource = schema.GroupVersionResource{Group: "arnob.com", Version: "v1alpha1", Resource: "messis"}

var messisKind = schema.GroupVersionKind{Group: "arnob.com", Version: "v1alpha1", Kind: "Messi"}

// Get takes name of the messi, and returns the corresponding messi object, and an error if there is any.
func (c *FakeMessis) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Messi, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(messisResource, c.ns, name), &v1alpha1.Messi{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Messi), err
}

// List takes label and field selectors, and returns the list of Messis that match those selectors.
func (c *FakeMessis) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MessiList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(messisResource, messisKind, c.ns, opts), &v1alpha1.MessiList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MessiList{ListMeta: obj.(*v1alpha1.MessiList).ListMeta}
	for _, item := range obj.(*v1alpha1.MessiList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested messis.
func (c *FakeMessis) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(messisResource, c.ns, opts))

}

// Create takes the representation of a messi and creates it.  Returns the server's representation of the messi, and an error, if there is any.
func (c *FakeMessis) Create(ctx context.Context, messi *v1alpha1.Messi, opts v1.CreateOptions) (result *v1alpha1.Messi, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(messisResource, c.ns, messi), &v1alpha1.Messi{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Messi), err
}

// Update takes the representation of a messi and updates it. Returns the server's representation of the messi, and an error, if there is any.
func (c *FakeMessis) Update(ctx context.Context, messi *v1alpha1.Messi, opts v1.UpdateOptions) (result *v1alpha1.Messi, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(messisResource, c.ns, messi), &v1alpha1.Messi{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Messi), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMessis) UpdateStatus(ctx context.Context, messi *v1alpha1.Messi, opts v1.UpdateOptions) (*v1alpha1.Messi, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(messisResource, "status", c.ns, messi), &v1alpha1.Messi{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Messi), err
}

// Delete takes name of the messi and deletes it. Returns an error if one occurs.
func (c *FakeMessis) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(messisResource, c.ns, name, opts), &v1alpha1.Messi{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMessis) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(messisResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MessiList{})
	return err
}

// Patch applies the patch and returns the patched messi.
func (c *FakeMessis) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Messi, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(messisResource, c.ns, name, pt, data, subresources...), &v1alpha1.Messi{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Messi), err
}
